name: Upload Mac App to BunnyCDN

on:
  push:
    branches: [ main ]
    paths:
      - 'Distribution/TNT.dmg'
  workflow_dispatch:

jobs:
  upload_mac:
    runs-on: macos-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload to BunnyCDN
        run: |
          curl -X PUT \
            -H "AccessKey: ${{ secrets.BUNNY_ACCESS_KEY }}" \
            --data-binary "@Distribution/TNT.dmg" \
            "https://se.storage.bunnycdn.com/sw-stor/TNT.dmg"
